repository: avast/avast.github.io
gems:
  - jekyll-github-metadata

selected_repositories:
  Java/Scala libraries & tools:
    - rabbitmq-scala-client
    - cactus
    - metrics
    - bytes
    - gradle-dependencies-viewer
    - scala-hashes
    - grpc-json-bridge
  Docker, Kubernetes & cloud tools:
    - k8s-admission-webhook
    - gradle-docker-compose-plugin
    - marathon-vault-plugin
    - marathon-deployer
  Big data tools:
    - hdfs-shell
  Golang libraries & tools:
    - retry-go
    - hashutil-go
    - apkverifier
    - apkparser
    - teamcity-job-executor
  YARA tools:
    - yaramod
    - yls
    - yari
